on:
  push:
    branches:
      - master
    paths:
      - .all-contributorsrc

name: Site Deployment

jobs:
  invoke:
    name: Invoke
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Site Deployment
          repo: ScratchAddons/website-v2
          token: ${{ steps.generate-token.outputs.token }}